---
title: "BQL Data Analysis"
author: "Jackie & Mia"
date: "2025-04-11"
output: html_document
---

# Objective

To pull up the descriptives/demographic data for the Black, Queer & Liberated mental health intervention project. This is part of Jacquelyn Chin's 2025 dissertation defense. Almost at the finish line, baddie!!

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
options(knitr.duplicate.label = "allow",
        scipen = 999)

#install packages if necessary, then load libraries
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}
librarian::shelf(
  here, #for file paths
  janitor, #for column name cleaning
  lubridate, #for working with dates 
  readxl, #read in Excel files
  tidyverse, #general data cleaning functions and collection of common packages
  writexl #save Excel files
  )
```

# Read in the data
### Command + option + I makes a code chunk appear on the Mac
- Race/Ethnicity 

```{r read_in_race}
#filepath & here function takes everything in green & helps R locate the correct file path
filepath <- here("../")
#"../" means one file outside of this file
print(filepath)
#filename function tells R where the exact file is located
filename <- list.files(path = filepath, 
                        pattern = "BQL Survey Data - CLEAN.xlsx")
print(filename)
#print function means 'show me what is in thie file'

BQL_Data <- read_excel(path = here(filepath, filename[1]), sheet = 1) 
```






